version: '3'

services:
  notebook:
    build:
      context: ./dir/
      dockerfile: .docker/Dockerfile
      args: 
        UID: ${LOCALUID}
        GID: ${LOCALGID}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # GPUの枚数
              capabilities: [gpu]
    environment:
      TZ: Asia/Tokyo
    ports:
      # notebook用(デフォルトは 8888)
      - ${JUPYTER_LAB_PORT}:8888
      # TensorBoard用 (デフォルトは 6006)
      - ${TENSORBOARD_PORT}:6006
    volumes:
      - ./dir:/home/nb-user
      - /home/ksl_pub/suggestive_anger:/home/nb-user/ksl_pub/suggestive_anger
    # dns:
    #   - 127.0.1.1
    #   - 8.8.8.8
    #   - 8.8.4.4
    # dns_search: nagaokaut.ac.jp
    tty: true
    env_file:
      - ./.env
